#!/bin/sh
#
# $Id: lt,v 1.3 1995/04/24 19:51:50 gurin Exp $
#
if [ -n "$2" ]; then
  bad=true
fi
if [ "$1" != "c" -a "$1" != "com" -a "$1" != "c++" -a "$1" != "sh" ]; then
  bad=true
fi
if [ -n "$bad" ]; then
  echo "Format: $0 { c | c++ | com | sh }"
  exit 1
fi
mode=$1
awk 'BEGIN { mode="'"$mode"'" }
{ 
l=length($0)
if( mode == "sh" )
  print $0;
else if( mode == "com" )
  print "$!" $0;
else if( mode == "c" )
  print "/*" substr($0,2,l-2) "*/" 
else if( mode == "c++" )
  print "//" substr($0,2,l-2) "//" 
}' << EOF
############################################################################
#                                                                          #
# Copyright (c) 1993-1994 CASPUR Consortium                                #
#                         c/o Universita' "La Sapienza", Rome, Italy       #
# All rights reserved.                                                     #
#                                                                          #
# Permission is hereby granted, without written agreement and without      #
# license or royalty fees, to use, copy, modify, and distribute this       #
# software and its documentation for any purpose, provided that the        #
# above copyright notice and the following two paragraphs and the team     #
# reference appear in all copies of this software.                         #
#                                                                          #
# IN NO EVENT SHALL THE CASPUR CONSORTIUM BE LIABLE TO ANY PARTY FOR       #
# DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES ARISING  #
# OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN IF THE       #
# CASPUR CONSORTIUM HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.    #
#                                                                          #
# THE CASPUR CONSORTIUM SPECIFICALLY DISCLAIMS ANY WARRANTIES,             #
# INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY #
# AND FITNESS FOR A PARTICULAR PURPOSE.  THE SOFTWARE PROVIDED HEREUNDER   #
# IS ON AN "AS IS" BASIS, AND THE CASPUR CONSORTIUM HAS NO OBLIGATION TO   #
# PROVIDE MAINTENANCE, SUPPORT, UPDATES, ENHANCEMENTS, OR MODIFICATIONS.   #
#                                                                          #
#       +----------------------------------------------------------+       #
#       |   The ControlHost Team: Ruten Gurin, Andrei Maslennikov  |       #
#       |   Contact e-mail      : ControlHost@caspur.it            |       #
#       +----------------------------------------------------------+       #
#                                                                          #
############################################################################
EOF
